version: "3.8"
services:
  #nginx
  webserver:
    image: nginx:latest
    container_name: ads_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dockerfiles/nginx/error_log:/etc/nginx/error_log
      - ./dockerfiles/nginx/access_log:/etc/nginx/access_log
      - .env:/var/www/html/.env
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - amydressshop

  #mysql
  mysql:
    image: mysql:8.0.21
    container_name: ads_mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASS: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "33061:3306"
    volumes:
      - ./dockerfiles/mysql/data:/var/lib/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/conf.d/mysql-custom.cnf
    networks:
      - amydressshop
  #php
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php/php.dockerfile
    container_name: ads_php
    volumes:
      - .:/var/www/dockerfiles
      - ./xdebug:/var/www/xdebug
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./ads_app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - amydressshop

  composer:
    image: composer:latest
    container_name: ads_composer
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
    working_dir: /var/www/html
    command: [composer, install]
    networks:
      - amydressshop

  #npm
  npm:
    image: node:21-alpine3.18
    container_name: ads_node
    volumes:
      - .:/var/www/dockerfiles
      - ./ads_app:/var/www/html
    ports:
      - "5173:5173"
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
    networks:
      - amydressshop

  artisan:
    build:
      context: .
      dockerfile: ./dockerfiles/php/php.dockerfile
    container_name: ads_artisan
    volumes:
      - .:/var/www/dockerfiles
      - ./xdebug:/var/www/xdebug
      - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./ads_app:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

networks:
  amydressshop:
